---
- name: Diagnóstico comandos no servidor
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Testar comando mysql -V
      shell: which mysql && mysql -V
      register: mysql_test
      ignore_errors: yes

    - name: Testar comando df
      shell: which df && df -h /
      register: df_test
      ignore_errors: yes

    - name: Testar comando free
      shell: which free && free -h
      register: free_test
      ignore_errors: yes

    - name: Testar comando uptime
      shell: which uptime && uptime -p
      register: uptime_test
      ignore_errors: yes

    - name: Testar comando hostname -I
      shell: which hostname && hostname -I
      register: ip_test
      ignore_errors: yes

    - name: Testar comando who
      shell: which who && who | wc -l
      register: who_test
      ignore_errors: yes

    - name: Mostrar todos os resultados
      debug:
        msg: |
          MYSQL: {{ mysql_test.stdout }}
          DF: {{ df_test.stdout }}
          FREE: {{ free_test.stdout }}
          UPTIME: {{ uptime_test.stdout }}
          IP: {{ ip_test.stdout }}
          USERS: {{ who_test.stdout }}
