- name: Coletar dados do servidor com shell interativo
  hosts: all
  gather_facts: no
  become: yes

  tasks:

    - name: Versão do MariaDB
      shell: ". /etc/profile && mysql -V"
      register: mysql_version
      ignore_errors: yes

    - name: Espaço em disco
      shell: ". /etc/profile && df -h /"
      register: disk_usage
      ignore_errors: yes

    - name: Uso de memória
      shell: ". /etc/profile && free -h"
      register: mem_usage
      ignore_errors: yes

    - name: Uptime
      shell: ". /etc/profile && uptime -p"
      register: uptime_info
      ignore_errors: yes

    - name: IP do servidor
      shell: ". /etc/profile && hostname -I | awk '{print $1}'"
      register: ip_info
      ignore_errors: yes

    - name: Usuários conectados
      shell: ". /etc/profile && who | wc -l"
      register: user_count
      ignore_errors: yes

    - name: Exibir resultado final
      debug:
        msg: |
          ======= DADOS DO SERVIDOR {{ inventory_hostname }} =======
          MySQL: {{ mysql_version.stdout | default('N/A') }}
          Espaço em disco: {{ disk_usage.stdout | default('N/A') }}
          Memória: {{ mem_usage.stdout | default('N/A') }}
          Uptime: {{ uptime_info.stdout | default('N/A') }}
          IP: {{ ip_info.stdout | default('N/A') }}
          Usuários conectados: {{ user_count.stdout | default('N/A') }}
