---
- name: Coletar dados do servidor
  hosts: all
  gather_facts: yes
  become: yes

  tasks:

    - name: Obter versão do MySQL
      shell: mysql -V
      register: mysql_version
      ignore_errors: yes

    - name: Obter espaço em disco
      shell: df -h /
      register: disk_space

    - name: Obter uso de memória
      shell: free -h
      register: memory_info

    - name: Obter uptime do servidor
      shell: uptime -p
      register: uptime_info

    - name: Obter IP do servidor
      shell: hostname -I | awk '{print $1}'
      register: ip_address

    - name: Obter número de usuários conectados
      shell: who | wc -l
      register: user_count

    - name: Exibir informações coletadas
      debug:
        msg: |
          ======= DADOS DO SERVIDOR =======
          Versão do MySQL: {{ mysql_version.stdout | default('Erro ao obter') }}
          Espaço em disco (/): 
          {{ disk_space.stdout }}
          Memória:
          {{ memory_info.stdout }}
          Uptime:
          {{ uptime_info.stdout }}
          IP do servidor: {{ ip_address.stdout }}
          Usuários conectados: {{ user_count.stdout }}
