- name: Verificar versão do Linux
  hosts: all
  gather_facts: no
  become: false

  tasks:
    - name: Obter versão do Linux (linha PRETTY_NAME)
      shell: awk -F= '/^PRETTY_NAME/ {gsub(/"/, "", $2); print $2}' /etc/os-release
      register: linux_pretty_name

    - name: Exibir nome e versão do Linux
      debug:
        msg: "Servidor {{ inventory_hostname }} está rodando: {{ linux_pretty_name.stdout }}"
